volumes:
  data:
  export:
networks:
  idm_network:

services:
  postgres-db:
    build:
      context: .
      dockerfile: dockerfile
    container_name: postgres-server
    hostname: postgres-db
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
      - ../migrations:/migrations
    networks:
      - idm_network